# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-21 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
