# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-11-21 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mus', '0004_auto_20161121_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='rating',
        ),
    ]
